# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
        environment:
            PGHOST: 127.0.0.1
            PGUSER: sharepay2dfh-test
            SSLPG: false

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: sharepay2dfh-test
          POSTGRES_DB: sharepay2dfh-test
          POSTGRES_PASSWORD: ""
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - store_artifacts:
          path: ./sql/dump.sql
          destination: artifact-file

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: sudo apt-get update

      - run: sudo apt install --fix-missing postgresql-client

      - run:
          name: dump DB
          command: sudo psql --host 127.0.0.1 --port 5432 --username sharepay2dfh-test -d sharepay2dfh-test -f artifact-file

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
